version: '2'

services:
  config-server:
    image: "config-server:latest"
    mem_limit: 512m
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    networks:
      - test
  eureka-server:
    image: "eureka-server:latest"
    mem_limit: 512m
    ports:
      - "8882:8882"
    networks:
      - test
  admin:
    image: "admin:latest"
    mem_limit: 512m
    ports:
      - "8880:8880"
    depends_on:
      - eureka-server
    networks:
      - test
  portainer:
    image: "portainer/portainer:latest"
    ports:
      - "9000:9000"
    networks:
      - test
networks:
  test:
    driver: bridge