spring:
  application:
    name: second
  rabbitmq:
    host: rabbit
    username: rabbitmq
    password: rabbitmq
  cloud:
    inetutils:
      preferred-networks: 192,10.0
      timeout-seconds: 5

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    status-page-url-path: ${server.servlet.context-path}/actuator/info
    health-check-url-path: ${server.servlet.context-path}/actuator/health
    metadata-map:
      management.context-path: ${server.servlet.context-path}/actuator
      startup: ${random.int}    #needed to trigger info and endpoint update after restart
  client:
    service-url:
      defaultZone: ${eureka.host}
    register-with-eureka: true
    registry-fetch-interval-seconds: 10
  host: http://eureka-server:8882/service-registry/eureka/

server:
  servlet:
    context-path: /second
  port: 8884