application:
  name: second

server:
  servlet:
    context-path: /second
  port: 8884

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    status-page-url-path: ${server.servlet.context-path}/actuator/info
    health-check-url-path: ${server.servlet.context-path}/actuator/health
    metadata-map:
      management.context-path: ${server.servlet.context-path}/actuator
      startup: ${random.int}    #needed to trigger info and endpoint update after restart
  client:
    service-url:
      defaultZone: ${eureka.host}
    register-with-eureka: true
  host: http://localhost:8882/service-registry/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
  info:
    git:
      mode: full